project:
  type: website

website:
  title: ''
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications
        text: Publications

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
